
InterviewPt1::
    .string "Hello!\p"
    .string "I presume you are here\n"
    .string "for the interview?\p"
    .string "Excellent!\p"
    .string "What was your name?\p"
    .string "...\n"
    .string "{PLAYER}, nice to meet you!\p"
    .string "My name is Arthur, and these\n"
    .string "are my friends Jan and Hank.\p"
    .string "May we take a look at your\n"
    .string "resume please?$"

GiveResume::
    .string "{PLAYER} handed Arthur\n"
    .string "the resume$"

InterviewPt2::
    .string "...\n"
    .string "...\n"
    .string "Well...\p"
    .string "This is quite the resume!\p"
    .string "Now we want to ask you\n"
    .string "a few questions...\p"
    .string "Are you ready?$"

SSAnne_1F_Room5_Text_ArthurIntro:: @ 8173BD1
    .string "Are you ready?$"

SSAnne_1F_Room5_Text_ArthurDefeat:: @ 8173BFA
    .string "Well said!$"

SSAnne_1F_Room5_Text_ArthurPostBattle:: @ 8173C30
    .string "You answered all of\n"
    .string "our questions perfectly!$"

PostBattle1::
    .string "Now, if you would step outside\n"
    .string "for just--$"

AbbySpeak::
    .string "Abby: Daddy Daddy Daddy!!\p"
    .string "Are you almost done yet?$"

IknowYou::
    .string "Hey, I know you!\p"
    .string "You are the meanie head\n"
    .string "that didn't want to play with me!\p"

Failed::
    .string "Arthur: He treated you\n"
    .string "like that??\p"
    .string "I'm sorry, {PLAYER}\p"
    .string "I don't think you have\n"
    .string "what it takes to work\l"
    .string "to work in this company...$"

HiPlayer::
    .string "Oh, hi {PLAYER}!\p"
    .string "Daddy, {PLAYER} is my friend!\p"
    .string "We played together on Route 18\n"
    .string "earlier this morning.$"

Succeed::
    .string "Wow, {PLAYER} you did that?\p"
    .string "Ever since we moved, my daughter\n"
    .string "has had a very difficult time\l"
    .string "making friends and fitting in\p"
    .string "Thank you so much for taking!\n"
    .string "the time to befriend my daughter.\p"
    .string "I think that settles it for everyone!\n"
    .string "{PLAYER}, welcome to the team!\l"
    .string "We start work in June!$"
