.equ LOCALID_JOCK, 1

CeladonCity_DepartmentStore_2F_MapScripts:: @ 816BAF4
	.byte 0

CeladonCity_Jock_Script::
	lock
	msgbox Jock_HeyShrimp
	applymovement OBJ_EVENT_ID_PLAYER, Movement_ExclamationMark
	waitmovement 0
	setvar VAR_MAP_SCENE_SAFFRON_CITY_DOJO, 1
	call Jack_WalktoPlayer_Script
	call SaffronCity_Dojo_EventScript_Hitoshi
	msgbox Jock_Finish
	release
	end

Jack_WalktoPlayer_Script::
	applymovement OBJ_EVENT_ID_PLAYER, Jack_WalktoPlayer
	waitmovement 0
	return

Jack_WalktoPlayer:
	walk_down
	walk_down
	walk_down
	walk_down
	walk_right
	walk_down
	walk_down
	walk_right
	walk_in_place_fast_up
	step_end


VermilionCity_PokemonFanClub_EventScript_Pikachu:: @ 816B59E
	lock
	faceplayer
	waitse
	playmoncry SPECIES_PIKACHU, 0
	msgbox VermilionCity_PokemonFanClub_Text_Pikachu
	waitmoncry
	release
	end




CeladonCity_DepartmentStore_2F_EventScript_UnusedNPC:: @ 816BAF5
	msgbox CeladonCity_DepartmentStore_2F_Text_SuperRepelMorePowerfulRepel, MSGBOX_NPC
	end

CeladonCity_DepartmentStore_2F_EventScript_Lass:: @ 816BAFE
	msgbox CeladonCity_DepartmentStore_2F_Text_BuyReviveForLongOutings, MSGBOX_NPC
	end

CeladonCity_DepartmentStore_2F_EventScript_FloorSign:: @ 816BB07
	msgbox CeladonCity_DepartmentStore_2F_Text_FloorSign, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_2F_EventScript_ClerkItems:: @ 816BB10
	goto_if_questlog EventScript_ReleaseEnd
	lock
	faceplayer
	message Text_MayIHelpYou
	waitmessage
	pokemart CeladonCity_DepartmentStore_2F_Items
	msgbox Text_PleaseComeAgain
	release
	end

	.align 2
CeladonCity_DepartmentStore_2F_Items:: @ 816BB38
	.2byte ITEM_SUPER_POTION
	.2byte ITEM_MAX_POTION
	.2byte ITEM_REVIVE
	.2byte ITEM_PARALYZE_HEAL
	.2byte ITEM_AWAKENING
	.2byte ITEM_BURN_HEAL
	.2byte ITEM_NONE
	release
	end

CeladonCity_DepartmentStore_2F_EventScript_ClerkTMs:: @ 816BB4E
	goto_if_questlog EventScript_ReleaseEnd
	lock
	faceplayer
	message Text_MayIHelpYou
	waitmessage
	pokemart CeladonCity_DepartmentStore_2F_TMs
	msgbox Text_PleaseComeAgain
	release
	end

	.align 2
CeladonCity_DepartmentStore_2F_TMs:: @ 816BB74
	.2byte ITEM_TM05
	.2byte ITEM_TM15
	.2byte ITEM_TM28
	.2byte ITEM_TM31
	.2byte ITEM_TM43
	.2byte ITEM_TM45
	.2byte ITEM_NONE
	release
	end
