Jock_HeyShrimp::
    .string "HEY SHRIMP!\n"
    .string "Get over here.$"

Jock_Finish::
    .string "So what you're saying is that\n"
    .string "whenever I am giving criticism,\p"
    .string "I should compliment them first?\p"
    .string "Then, I try to make suggestions their idea\n"
    .string "so they are more motivated to do it?\p"
    .string "...\n"
    .string "Is that right?\p"
    .string "HAHA look at you using your own tactics on me.\p"
    .string "That's fighting like a true\p"
    .string "karate master right there!$"

CeladonCity_DepartmentStore_2F_Text_SuperRepelMorePowerfulRepel:: @ 81955C7
    .string "SUPER REPEL keeps weak POKéMON at\n"
    .string "bay…\p"
    .string "Hmm, it's a more powerful REPEL.$"

CeladonCity_DepartmentStore_2F_Text_BuyReviveForLongOutings:: @ 819560F
    .string "For long outings, you should buy\n"
    .string "REVIVE.$"

CeladonCity_DepartmentStore_2F_Text_FloorSign:: @ 8195638
    .string "Top-Grade Items for TRAINERS!\p"
    .string "2F: TRAINER'S MARKET$"

CeladonCity_DepartmentStore_2F_Text_LanceComesToBuyCapes:: @ 819566B
    .string "We have a customer, LANCE, who\n"
    .string "occasionally comes.\p"
    .string "He always buys capes.\p"
    .string "I wonder… Does he have many\n"
    .string "identical capes at home?$"
