SaffronCity_Dojo_Text_MasterKoichiIntro:: @ 819B12C
    .string "Grunt!\p"
    .string "I am the KARATE MASTER!\n"
    .string "I am the LEADER here!\p"
    .string "You wish to challenge us?\n"
    .string "Expect no mercy!\p"
    .string "Fwaaa!$"

SaffronCity_Dojo_Text_MasterKoichiDefeat:: @ 819B193
    .string "Hwa!\n"
    .string "Arrgh! Beaten!$"

SaffronCity_Dojo_Text_ChoosePrizedFightingMon:: @ 819B1A7
    .string "Indeed, I have lost!\p"
    .string "But, I beseech you, do not take\n"
    .string "our emblem as your trophy!\p"
    .string "In return, I will give you a prized\n"
    .string "FIGHTING POKéMON!\p"
    .string "Choose whichever one you like!$"

SaffronCity_Dojo_Text_StayAndTrainWithUs:: @ 819B24C
    .string "Grunt!\n"
    .string "Stay and train at karate with us!$"

SaffronCity_Dojo_Text_MikeIntro:: @ 819B275
    .string "Hoargh!\n"
    .string "Take your shoes off!$"

SaffronCity_Dojo_Text_MikeDefeat:: @ 819B292
    .string "I give up!$"

SaffronCity_Dojo_Text_MikePostBattle:: @ 819B29D
    .string "You wait 'til you see our MASTER!\n"
    .string "I'm a small fry compared to him!$"

SaffronCity_Dojo_Text_HidekiIntro:: @ 819B2E0
    .string "I hear you're good!\n"
    .string "Show me!$"

SaffronCity_Dojo_Text_HidekiDefeat:: @ 819B2FD
    .string "Judge!\n"
    .string "One point!$"

SaffronCity_Dojo_Text_HidekiPostBattle:: @ 819B30F
    .string "Our MASTER is a pro fighter.\n"
    .string "Be prepared to lose!$"

SaffronCity_Dojo_Text_AaronIntro:: @ 819B341
    .string "Hiyah!\n"
    .string "I have no fear for anything tough!\p"
    .string "I shatter boulders for training\n"
    .string "every day!$"

SaffronCity_Dojo_Text_AaronDefeat:: @ 819B396
    .string "Yow!\n"
    .string "Stubbed fingers!$"

SaffronCity_Dojo_Text_AaronPostBattle:: @ 819B3AC
    .string "The only thing that frightens us is\n"
    .string "psychic power!$"

SaffronCity_Dojo_Text_HitoshiIntro:: @ 819B3DF
    .string "I have a problem here...\p"
    .string "I am a personal trainer\n"
    .string "at this gym.\p"
    .string "A lot of my clients have been\n"
    .string "complaining that I am overly critical...\p"
    .string "You seem like a sociable fellow.\n"
    .string "How can I treat my clients better?$"

SaffronCity_Dojo_Text_HitoshiDefeat:: @ 819B40F
    .string "Hey! That sounds like a great idea.$"

SaffronCity_Dojo_Text_HitoshiPostBattle:: @ 819B41F
    .string "So what you're saying is that\n"
    .string "whenever I am giving criticism,\p"
    .string "I should compliment them first?\p"
    .string "Then, I should try to make any\n"
    .string "suggestions their idea, so that\l"
    .string "they are more motivated to do it?\p"
    .string "...\n"
    .string "Is that right?\p"
    .string "HA!\n"
    .string "You just did the same trick on me!\p" 
    .string "That's as clever as a true\n"
    .string "karate master right there!$"

SaffronCity_Dojo_Text_YouWantHitmonlee:: @ 819B44E
    .string "You want the hard-kicking\n"
    .string "HITMONLEE?$"

SaffronCity_Dojo_Text_ReceivedMonFromKarateMaster:: @ 819B473
    .string "{PLAYER} received the {STR_VAR_1}\n"
    .string "from the KARATE MASTER.$"

SaffronCity_Dojo_Text_YouWantHitmonchan:: @ 819B49E
    .string "You want the piston-punching\n"
    .string "HITMONCHAN?$"

SaffronCity_Dojo_Text_ReceivedMonFromKarateMaster2:: @ 819B4C7
    .string "{PLAYER}は　カラテ　だいおう　から\n"
    .string "{STR_VAR_1}を　もらった！$"

SaffronCity_Dojo_Text_BetterNotGetGreedy:: @ 819B4E1
    .string "Better not get greedy…$"

SaffronCity_Dojo_Text_EnemiesOnEverySide:: @ 819B4F8
    .string "Enemies on every side!$"

SaffronCity_Dojo_Text_GoesAroundComesAround:: @ 819B50F
    .string "What goes around comes around.$"

SaffronCity_Dojo_Text_FightingDojo:: @ 819B52E
    .string "FIGHTING DOJO$"

