CeladonCity_DepartmentStore_5F_Text_ExplainStatEnhancers:: @ 8195BBA
    .string "POKéMON stat enhancers can be\n"
    .string "bought only here.\p"
    .string "HP UP increases the base HP of a\n"
    .string "POKéMON.\p"
    .string "CALCIUM raises the base SP. ATK\n"
    .string "stat of one POKéMON.\p"
    .string "ZINC boosts the base SP. DEF stat\n"
    .string "of one POKéMON.\p"
    .string "CARBOS enhances the base SPEED\n"
    .string "stat.$"

CeladonCity_DepartmentStore_5F_Text_HereForStatEnhancers:: @ 8195CA0
    .string "I'm here for POKéMON stat\n"
    .string "enhancers.\p"
    .string "PROTEIN increases the base ATTACK\n"
    .string "power.\p"
    .string "IRON increases the base DEFENSE\n"
    .string "stat.$"

CeladonCity_DepartmentStore_5F_Text_Drugstore:: @ 8195D14
    .string "5F: DRUGSTORE$"

receptionist:
    .string "Hello! Are you here\n"
    .string "for the interview?\p"
    .string "Perfect! Just head through\n"
    .string "that door to the left.\p"
    .string "They are waiting\n"
    .string "for you in there.$"

brokenelevator::
    .string "ELEVATOR OUT OF ORDER\n"
    .string "PLEASE TAKE THE STAIRS$"
    
