

RocketHideout_B4F_Text_Grunt2Intro:: @ 81753D0
    .string "I know you!\n"
    .string "You ruined our plans at MT. MOON!$"

RocketHideout_B4F_Text_Grunt2Defeat:: @ 81753FE
    .string "Burned again!$"

RocketHideout_B4F_Text_Grunt2PostBattle:: @ 817540C
    .string "Do you have something against TEAM\n"
    .string "ROCKET?$"

RocketHideout_B4F_Text_Grunt3Intro:: @ 8175437
    .string "How can you not see the beauty of\n"
    .string "our evil?$"

RocketHideout_B4F_Text_Grunt3Defeat:: @ 8175463
    .string "Ayaya!$"

RocketHideout_B4F_Text_Grunt3PostBattle:: @ 817546A
    .string "BOSS!\n"
    .string "I'm sorry I failed you!$"

RocketHideout_B4F_Text_Grunt1Intro:: @ 8175488
    .string "The elevator doesn't work?\n"
    .string "Who has the LIFT KEY?$"

RocketHideout_B4F_Text_Grunt1Defeat:: @ 81754B9
    .string "No!$"

RocketHideout_B4F_Text_Grunt1PostBattle:: @ 81754BD
    .string "Oh, no!\n"
    .string "I dropped the LIFT KEY!$"

