MtMoon_B2F_Text_MiguelIntro:: @ 8172B64
    .string "How should I talk to her\n"
    .string "so she will like me more?$"

MtMoon_B2F_Text_MiguelDefeat:: @ 8172B99
    .string "Okay!\n"
    .string "I'll test your hypothesis!$"

MtMoon_B2F_Text_WellEachTakeAFossil:: @ 8172BAB
    .string "What? You mean I shouldn't\n"
    .string "just talk about myself?\p"
    .string "Although I am not usually one to\n"
    .string "shirk from an opportunity to flex\l"
    .string "my superior intellect, I shall\l"
    .string "oblidge and focus on her instead.\p" 
    .string "I suppose if I enjoy talking about\n"
    .string "myself, others would too...\p"
    .string "It makes logical sense, after all!\p"
    .string "Ok, here I go!$"

MtMoon_B2F_Text_ThenThisFossilIsMine:: @ 8172BD6
    .string "All right.\n"
    .string "Then this fossil is mine!$"

MtMoon_B2F_Text_LabOnCinnabarRegeneratesFossils:: @ 8172BFB
    .string "Thanks again for the help,\n"
    .string "{PLAYER}.\p"
    .string "She is really starting to\n"
    .string "open up to me.\p"
    .string "I think she might even like me back!$"

MtMoon_B2F_Text_Grunt1Intro:: @ 8172C5A
    .string "We, TEAM ROCKET, shall find the\n"
    .string "fossils!\p"
    .string "Reviving POKéMON from them will\n"
    .string "earn us huge riches!$"

MtMoon_B2F_Text_Grunt1Defeat:: @ 8172CB8
    .string "Urgh!\n"
    .string "Now I'm mad!$"

MtMoon_B2F_Text_Grunt1PostBattle:: @ 8172CCB
    .string "You made me mad!\n"
    .string "TEAM ROCKET will blacklist you!$"

MtMoon_B2F_Text_Grunt2Intro:: @ 8172CFC
    .string "We, TEAM ROCKET, are POKéMON\n"
    .string "gangsters!\l"
    .string "We strike fear with our strength!$"

MtMoon_B2F_Text_Grunt2Defeat:: @ 8172D46
    .string "I blew it!$"

MtMoon_B2F_Text_Grunt2PostBattle:: @ 8172D51
    .string "Darn it all!\n"
    .string "My associates won't stand for this!$"

MtMoon_B2F_Text_Grunt3Intro:: @ 8172D82
    .string "We're pulling a big job here!\n"
    .string "Get lost, kid!$"

MtMoon_B2F_Text_Grunt3Defeat:: @ 8172DAF
    .string "So, you are good…$"

MtMoon_B2F_Text_Grunt3PostBattle:: @ 8172DC1
    .string "If you find a fossil, give it to me\n"
    .string "and scram!$"

MtMoon_B2F_Text_Grunt4Intro:: @ 8172DF0
    .string "Little kids shouldn't be messing\n"
    .string "around with grown-ups!\p"
    .string "It could be bad news!$"

MtMoon_B2F_Text_Grunt4Defeat:: @ 8172E3E
    .string "I'm steamed!$"

MtMoon_B2F_Text_Grunt4PostBattle:: @ 8172E4B
    .string "POKéMON lived here long before\n"
    .string "people came.$"

MtMoon_B2F_Text_YouWantDomeFossil:: @ 8172E77
    .string "Do you want the DOME FOSSIL?$"

MtMoon_B2F_Text_YouWantHelixFossil:: @ 8172E94
    .string "Do you want the HELIX FOSSIL?$"

MtMoon_B2F_Text_ObtainedHelixFossil:: @ 8172EB2
    .string "Obtained the HELIX FOSSIL!$"

MtMoon_B2F_Text_ObtainedDomeFossil:: @ 8172ECD
    .string "Obtained the DOME FOSSIL!$"

