Route24_Text_JustEarnedFabulousPrize:: @ 8188C3C
    .string "???: Hi! Nice to meet you.\n"
    .string "My name is Abby!\p"
    .string "What's your name?\p"
    .string "....\p"
    .string "{PLAYER}?\n"
    .string "Nice to meet you!\p"
    .string "The boys over there\n"
    .string "are being big meanies!$"

Route24_Text_ReceivedNuggetFromMysteryTrainer:: @ 8188C93
    .string "{PLAYER} received a doll\n"
    .string "from Abby!$"

Route24_Text_YouDontHaveAnyRoom:: @ 8188CC2
    .string "You don't have any room!$"

Route24_Text_JoinTeamRocket:: @ 8188CDB
    .string "This is fun!\p"
    .string "Let's play with our POKéMON!$"

Route24_Text_RocketDefeat:: @ 8188DDC
    .string "Wow!\n"
    .string "You are really good!$"

Route24_Text_YoudBecomeTopRocketLeader:: @ 8188DF1
    .string "That was FUN!\p"
    .string "Thank you for being my friend.\p"
	.string "I'll see you later {PLAYER}!$"

Text_FriendQuestion:
	.string "Will you be my friend?$"

Text_PlayerAnsweredNo:
	.string "Oh...\n"
	.string "...\p"
	.string "sniff\n"
	.string "You're a meanie too!$"

Route24_Text_YaytoBeingFriend:
    .string "Yay!\n"
	.string "That makes me so happy.\p"
	.string "You are really nice.\n"
	.string "Here, take this!$"






Route24_Text_ShaneIntro:: @ 8188E74
    .string "I saw your feat from the grass!$"

Route24_Text_ShaneDefeat:: @ 8188E94
    .string "I thought not!$"

Route24_Text_ShanePostBattle:: @ 8188EA3
    .string "I hid because the people on the\n"
    .string "bridge frightened me.$"

Route24_Text_EthanIntro:: @ 8188ED9
    .string "Okay! I'm No. 5!\n"
    .string "I'll stomp you!$"

Route24_Text_EthanDefeat:: @ 8188EFA
    .string "Whoa!\n"
    .string "Too much!$"

Route24_Text_EthanPostBattle:: @ 8188F0A
    .string "I did my best. I have no regrets!$"

Route24_Text_ReliIntro:: @ 8188F2C
    .string "I'm No. 4!\n"
    .string "Getting tired?$"

Route24_Text_ReliDefeat:: @ 8188F46
    .string "I lost, too!$"

Route24_Text_ReliPostBattle:: @ 8188F53
    .string "I did my best, so I've no regrets!$"

Route24_Text_TimmyIntro:: @ 8188F76
    .string "Here's No. 3!\n"
    .string "I won't be easy!$"

Route24_Text_TimmyDefeat:: @ 8188F95
    .string "Ow!\n"
    .string "Stomped flat!$"

Route24_Text_TimmyPostBattle:: @ 8188FA7
    .string "I did my best. I have no regrets!$"

Route24_Text_AliIntro:: @ 8188FC9
    .string "I'm second!\n"
    .string "Now it's serious!$"

Route24_Text_AliDefeat:: @ 8188FE7
    .string "How could I lose?$"

Route24_Text_AliPostBattle:: @ 8188FF9
    .string "I did my best. I have no regrets!$"

Route24_Text_CaleIntro:: @ 818901B
    .string "People call this the NUGGET\n"
    .string "BRIDGE!\p"
    .string "Beat us five TRAINERS and win\n"
    .string "a fabulous prize!\p"
    .string "Think you got what it takes?$"

Route24_Text_CaleDefeat:: @ 818908C
    .string "Whoo!\n"
    .string "Good stuff!$"

Route24_Text_CalePostBattle:: @ 818909E
    .string "I did my best. I have no regrets!$"

