CeladonCity_DepartmentStore_3F_Text_OTStandsForOriginalTrainer:: @ 81956E9
    .string "Captured POKéMON are registered\n"
    .string "with an ID No. and the OT.\p"
    .string "OT stands for “Original TRAINER” -\n"
    .string "the TRAINER that caught it first.$"

Nerd_Hey::
    .string "Hey, ummm...\n"
    .string "Do you think you could, ummm\p"
    .string" come over here, uhh, please?$"

Nerd_Situation::
    .string "Thanks for listening to me.\p"
    .string "It's not every day that\n"
    .string "someone wants to talk to\l"
    .string "a dweeb like me...\p"
    .string "Here's the situation:\n"
    .string "Do you see that girl\l"  
    .string "sitting behind me? \p"
    .string "I've got a huge crush on her. \p"
    .string "We've talked a few times,\n" 
    .string "but it still feels like I \l"
    .string "hardly know her!\p"
    .string "I'm usually not good at these\n" 
    .string "kinds of things, and you seem\l"
    .string "like you know what you're doing.\p"
    .string "Do you think you could help me out?$"


CeladonCity_DepartmentStore_3F_Text_BuddyTradingKangaskhanForHaunter:: @ 8195769
    .string "All right!\p"
    .string "My buddy's going to trade me his\n"
    .string "KANGASKHAN for my HAUNTER!$"

CeladonCity_DepartmentStore_3F_Text_HaunterEvolvedOnTrade:: @ 81957B0
    .string "Come on, HAUNTER!\p"
    .string "I love HAUNTER!\n"
    .string "I collect them!\p"
    .string "Huh?\p"
    .string "HAUNTER turned into a different\n"
    .string "POKéMON while being traded!$"

CeladonCity_DepartmentStore_3F_Text_CanIdentifyTradeMonsByID:: @ 8195823
    .string "You can identify POKéMON you get\n"
    .string "in trades by their ID Numbers.$"

CeladonCity_DepartmentStore_3F_Text_ItsSuperNES:: @ 8195863
    .string "It's a Super NES.$"

CeladonCity_DepartmentStore_3F_Text_AnRPG:: @ 8195875
    .string "An RPG!\n"
    .string "There's no time for that!$"

CeladonCity_DepartmentStore_3F_Text_SportsGame:: @ 8195897
    .string "A sports game!\n"
    .string "Dad'll like that!$"

CeladonCity_DepartmentStore_3F_Text_PuzzleGame:: @ 81958B8
    .string "A puzzle game!\n"
    .string "Looks addictive!$"

CeladonCity_DepartmentStore_3F_Text_FightingGame:: @ 81958D8
    .string "A fighting game!\n"
    .string "Looks tough!$"

CeladonCity_DepartmentStore_3F_Text_TVGameShop:: @ 81958F6
    .string "3F: TV GAME SHOP$"

CeladonCity_DepartmentStore_3F_Text_RedGreenBothArePokemon:: @ 8195907
    .string "Red and Green!\n"
    .string "Both are POKéMON!$"

CeladonCity_DepartmentStore_4F_Text_GettingPokeDollAsPresent:: @ 8195A68
    .string "I'm getting a present for my\n"
    .string "girlfriend.\p"
    .string "I guess a POKé DOLL will be it.\n"
    .string "It's the popular thing.$"