.equ LOCALID_GIOVANNI,    1
.equ LOCALID_SILPH_SCOPE, 2
.equ LOCALID_LIFT_KEY,    4
.equ LOCALID_OLD_DYING_MAN,  14

RocketHideout_B4F_Text_GiovanniIntro:: @ 8175226
    .string "Ah! You must be {PLAYER}!\p"
    .string "I must say, your reputation\n"
    .string "precedes you.\p"
    .string "News spreads fast in this\n"
    .string "office building.\p"
    .string "I heard you helped some\n"
    .string "individuals learn how to be\l"
    .string "nicer to other people.\p"
    .string "How cute.\p"
    .string "I know you are here to look\n"
    .string "for a job.\p"
    .string "Even if we did have any openings,\n"
    .string "there is no way I would hire\l"
    .string "someone as soft as you.\p"
    .string "Business people need to be\n"
    .string "cold and calculating, not\l"
    .string "sensitive and meek.\p"
    .string "What?\p"
    .string "You dare to disagree with me?\p"
    .string "For your insolence, you will feel a\n"
    .string "world of pain!$"

RocketHideout_B4F_Text_GiovanniDefeat:: @ 8175318
    .string "Hmm...\n"
    .string "Maybe there is another way.$"

RocketHideout_B4F_Text_GiovanniPostBattle:: @ 817532D
    .string "...\p" 
    .string "All my life, I have used\n"
    .string "brute force to get people\l"
    .string "to do what I want.\p"
    .string "I've always been hated by my\n"
    .string "subordinates.\p"
    .string "I thought it was just\n"
    .string "part of the job.\p"
    .string "Now I can see that people don't\n"
    .string "need to be forced to have the \l"
    .string "desire to excel in their job.\p"
    .string "If I appeal to their nobler\n"
    .string "motives, they will want to\l"
    .string "improve on their own.\p"
    .string "...\p" 
    .string "Perhaps I misjudged you.\p"
    .string "I would hire you, but I gave my\n"
    .string "last open position to {RIVAL}.\p"
    .string "However, if you head upstairs,\n"
    .string "they should still have one more\l"
    .string "slot available for an intern.\p"
    .string "If your POKéMON's health is low,\n"
    .string "you can purchase POTIONs from\l"
    .string "one of my workers\p"
    .string "Good luck!\p"
    .string "I hope we meet again…$"


CeladonCity_DepartmentStore_4F_Text_CanRunAwayWithPokeDoll:: @ 8195AC9
    .string "I heard something useful.\p"
    .string "If a wild POKéMON appears, you can\n"
    .string "distract it with a POKé DOLL.\p"
    .string "You can run away while the wild\n"
    .string "POKéMON is distracted.$"

CeladonCity_DepartmentStore_4F_Text_FloorSign:: @ 8195B5B
    .string "Express yourself with gifts!\n"
    .string "4F: WISE MAN GIFTS\p"
    .string "Evolution Special!\n"
    .string "Element STONES on sale now!$"

old_man_dying::
    .string "So... tired...\p"
    .string "No...breaks...\p"
    .string "Must...quit...\n"
    .string "terrible job...$"
