PalletTown_Text_OakDontGoOut:: @ 817D72C
    .string "Prof. Anderson: Hey! Wait!\n"
    .string "Winter break isn't here yet!$"

PalletTown_Text_OakGrassUnsafeNeedMon:: @ 817D74A
    .string "Before you start interviewing\n"
    .string "for summer internships,\p"
    .string "you need your own POKéMON to\n"
    .string "help you win friends and\l"
    .string "influence people.\p"
    .string "I know!\n"
    .string "Here, come with me!$"

PalletTown_Text_RaisingMonsToo:: @ 817D7C8
    .string "I'm raising POKéMON, too.\p"
    .string "When they get strong, they can\n"
    .string "protect me.$"

PalletTown_Text_CanStoreItemsAndMonsInPC:: @ 817D80D
    .string "Technology is incredible!\p"
    .string "You can now store and recall items\n"
    .string "and POKéMON as data via PC.$"

PalletTown_Text_OakPokemonResearchLab:: @ 817D866
    .string "OAK POKéMON RESEARCH LAB$"

PalletTown_Text_PlayersHouse:: @ 817D87F
    .string "{PLAYER}'s house$"

PalletTown_Text_RivalsHouse:: @ 817D88A
    .string "{RIVAL}'s house$"

PalletTown_Text_TownSign:: @ 817D895
    .string "PALLET TOWN\n"
    .string "Shades of your journey await!$"

PalletTown_Text_OakLetMeSeePokedex:: @ 817D8BF
    .string "Prof. Anderson: Ah, {PLAYER}!\n"
    .string "You're back, are you?\p"
    .string "How much have you filled in your\n"
    .string "POKéDEX?\p"
    .string "May I see it?\p"
    .string "Let's see…$"

PalletTown_Text_CaughtXPuttingInHonestEffort:: @ 817D925
    .string "You've caught {STR_VAR_2}…\p"
    .string "Hm, it looks as if you're putting\n"
    .string "in an honest effort.\p"
    .string "When you manage to fill it some\n"
    .string "more, come show me, please.$"

PalletTown_Text_CaughtXImpressiveFollowMe:: @ 817D9AA
    .string "You've caught… {STR_VAR_2}!?\n"
    .string "Now, this is impressive!\p"
    .string "There's something I wanted to ask\n"
    .string "of you, {PLAYER}.\p"
    .string "Come.\n"
    .string "Follow me.$"

PalletTown_Text_OakYouEnjoyingTraveling:: @ 817DA16
    .string "Prof. Anderson: Ah, {PLAYER}!\n"
    .string "You seem to be enjoying traveling.\p"
    .string "Knowing you, {PLAYER}, I can easily\n"
    .string "imagine you going out to even more\l"
    .string "exotic locales.\p"
    .string "Good for you, good for you.\n"
    .string "Hohoho.$"

